### ISSUE TITLE
Iron Mine didn't refill

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#2567]
![image](https://user-images.githubusercontent.com/32277970/47385159-42b0dd00-d6d7-11e8-8055-d7104130d193.png)

He tried to use an Iron Mine to save his Shrewd Yasuki from Aramoro.  This doesn't work, but he didn't realize that.  He then did the same thing with his other Iron Mine.

Neither refilled.

**Comment by jamesoddy** [comment]
Just so I have the game mechanics down for this.

I believe you should still be able to sacrifice Iron Mine to prevent the unit leaving play its just that the unit then just gets immediately discarded again by Aramoro.  Not sure why you would ever want to do that, but nevertheless I believe you should be able to sacrifice the Iron Mine.  Obviously the province should refill no matter what.

Does that sound right?

**Comment by jeremylarner** [comment]
I think this is fixed on master now, though I'm not sure whether the patched code has been deployed to the server yet or not

**Comment by YogoGohei** [comment]
Yes, the Mine / Aramoro interaction worked correctly.  Doing it doesn't make sense, but he was confused about how that interaction worked.  I would have let him take it back if there was a way to refill provinces from his discard pile.

That is all beside the point.

The issue is the mine didn't refill.

I included that extra info in case that was the cause of the problem.

**Comment by jamesoddy** [comment]
Hopefully fixed already, but I will get round to writing a test to confirm.  As for the refilling manually, this is related to issue #2541 and to an extent #2542.  The extra info is very handy so please report as much as you can if you come across any issues.

**Comment by jamesoddy** [comment]
Looks as though it is still an issue (only for this particular case).  @jeremylarner can you help with a fix?  Please see PR #2569.
